API = 	../../API/builtin.c ../../API/dulbool.c ../../API/rangeobject.c ../../API/classobject.c ../../API/shapeobject.c ../../API/number.c ../../API/singleton.c	../../API/tuple.c ../../API/hashname.c ../../API/obimpl.c ../../API/strimpl.c  ../../API/array.c
all:
	gcc -I../.. json.c ${API} -fpic -shared -o ~/Dulang/NIolang/DLIB/json/json.so -g
